name: Python application
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  
on:
  push:
  # schedule:
  #   - cron: '0 4-12/1 * * *'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install Dependence
      run: pip install requests langchain openai pymupdf tiktoken datetime redis asyncio mutagen moviepy codecs arxiv edge_tts pdf2image

    - name: Run paper.py
      run: python ./paper.py

    
   
