name: Python application
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  
on:
  push:
  schedule:
    - cron: '0-12/30 * * * *'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install poppler
      run: sudo apt-get -y install poppler-utils
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install Dependence
      run: pip install requests langchain openai pymupdf tiktoken datetime redis asyncio mutagen moviepy arxiv edge_tts pdf2image bilibili-api-python

    - name: Run paper.py
      run: python ./paper.py

    
   
