name: Python application
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  apikey: ${{ secrets.apikey }}
  
on:
  push:
  schedule:
    - cron: '*/60 0-11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install poppler
      run: |
          sudo apt-get update 
          sudo apt-get install -y poppler-utils
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-recommended & sudo apt install texlive-pictures
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install Dependence
      run: pip install requests openai datetime redis asyncio mutagen moviepy edge_tts pdf2image bilibili-api-python nider Pillow==9.4.0 snownlp 

    - name: Run paper.py
      run: python paper.py



