name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install Dependence
      run: pip install requests langchain pinecone-client

    - name: Run paper.py
      run: python ./paper.py
    
   
